## KOCW 11주차 numpy의 이해

1) numpy 라이브러리는 수치 해석이나 통계 관련 기능에 특화  
2) 다른 파이썬 라이브러리들과 함께 사용되는 경우가 많음(pandas, matplotlib, scipy 등)  
3) 실행속도가 빠른 편

### numpy의 1차원 자료형 1
- 1차원적인 데이터 형식
- 파이썬의 리스트와 유사하나 벡터 연산이 가능함

In [1]:
import numpy as np

In [2]:
a = [10, 20, 30, 40, 50]

In [3]:
a

[10, 20, 30, 40, 50]

In [4]:
type(a)

list

In [5]:
b = np.array(a)

In [6]:
b

array([10, 20, 30, 40, 50])

In [7]:
print(b)

[10 20 30 40 50]


In [8]:
b.shape

(5,)

In [9]:
c = np.array([5,4,3,2,1])

In [10]:
c

array([5, 4, 3, 2, 1])

In [11]:
b + c

array([15, 24, 33, 42, 51])

In [12]:
b + 5

array([15, 25, 35, 45, 55])

In [13]:
a + 5    # 리스트에서는 위와 같은 연산 불가

TypeError: can only concatenate list (not "int") to list

In [14]:
a + [5,4,3,2,1]    # 리스트 + 리스트는 이어붙이는 형태로 연산이 진행됨

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

### numpy의 1차원 자료형 2
- 자주 사용하는 numpy 기본 함수
    - sum(): 합계
    - mean(): 평균
    - max(): 최댓값
    - min(): 최솟값
    - round(): 반올림
    - arange(): 리스트의 range()와 유사
    - zeros(): 0으로 이루어진 벡터
    - ones(): 1로 이루어진 벡터
    - copy(): 복사

In [15]:
np.sum(b)

150

In [16]:
np.mean(b)

30.0

In [17]:
np.max(b)

50

In [18]:
np.min(b)

10

In [19]:
c = b / 3

In [20]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [21]:
np.round(c, 1)    # 소수점 첫째자리까지 나타내라(둘째자리에서 반올림)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [22]:
np.round(c, 3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [23]:
np.round(c, 0)

array([ 3.,  7., 10., 13., 17.])

In [24]:
b[0]

10

In [25]:
b[-1]

50

In [26]:
b[1:3]

array([20, 30])

In [27]:
b[2:]

array([30, 40, 50])

In [28]:
np.sum(b[2:])

120

In [29]:
np.mean(b[2:])

40.0

In [30]:
b[1] = 200

In [31]:
b

array([ 10, 200,  30,  40,  50])

In [32]:
d = np.arange(5)

In [33]:
d

array([0, 1, 2, 3, 4])

In [34]:
e = np.arange(3,8)

In [35]:
e

array([3, 4, 5, 6, 7])

In [36]:
f = np.arange(3,8,2)

In [37]:
f

array([3, 5, 7])

In [38]:
g = np.zeros(5)

In [39]:
g

array([0., 0., 0., 0., 0.])

In [40]:
h = np.ones(5)

In [41]:
h

array([1., 1., 1., 1., 1.])

In [42]:
b

array([ 10, 200,  30,  40,  50])

In [43]:
bb = b    # b를 복사하는 것이 아니라 b의 위치를 복사하는 것

In [44]:
bb

array([ 10, 200,  30,  40,  50])

In [45]:
bb[0] = 100

In [46]:
bb

array([100, 200,  30,  40,  50])

In [47]:
b    # 따라서 bb 뿐만 아니라 b 또한 바뀜

array([100, 200,  30,  40,  50])

In [48]:
b == bb

array([ True,  True,  True,  True,  True])

In [49]:
bb = b.copy()    # 복사해서 저장

In [50]:
bb

array([100, 200,  30,  40,  50])

In [51]:
b[2] = 300

In [52]:
b

array([100, 200, 300,  40,  50])

In [53]:
bb

array([100, 200,  30,  40,  50])

In [54]:
b == bb

array([ True,  True, False,  True,  True])

### Numpy의 2차원 자료형
- 2차원적인 데이터 형식
- 행렬 연산이 가능

In [55]:
import numpy as np

In [56]:
a = np.array([[10,20,30,40,],[50,60,70,80]])

In [57]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [58]:
a.shape

(2, 4)

In [59]:
b, c = a.shape

In [60]:
b

2

In [61]:
c

4

In [62]:
a[0,0]

10

In [63]:
a[-1,-1]

80

In [64]:
a[1,1:]

array([60, 70, 80])

In [65]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [66]:
a[0, 1] = 2

In [67]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [68]:
b = np.zeros((2,4))

In [69]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
c = np.ones((3,5))

In [71]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
c = np.arange(8)

In [73]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
c.reshape(2,4)    # 값을 변경하지는 않는다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
c = c.reshape(2,4)

In [77]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
c = c.reshape(4,2)

In [79]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [80]:
c.sum()

28

In [81]:
d = c.copy()

In [82]:
d[0, 0] = 10

In [83]:
d

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [84]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [85]:
c == d

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [86]:
e = np.arange(49).reshape(7,7)

In [87]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [88]:
e[:,1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [89]:
e[3:, :4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [90]:
e[3:, :4].sum()

528

In [91]:
f = e[3:,:4].copy()

In [92]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [93]:
e[4,0] = 100

In [94]:
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [95]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [96]:
f.sum()

528

### Numpy의 기본 연산과 조건 처리1
- Numpy의 기본 연산
    - 사칙연산(+,-,*,/,//,%)
    - 스칼라곱, 행렬곱
- Numpy의 조건 처리

In [97]:
import numpy as np

In [98]:
a = np.arange(5, 45, 5).reshape(2, 4)

In [99]:
b = np.arange(20, 36, 2).reshape(2, 4)

In [100]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [101]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [102]:
a + b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [103]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [104]:
b - a

array([[15, 12,  9,  6],
       [ 3,  0, -3, -6]])

In [105]:
a * b

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [106]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [107]:
a // b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int32)

In [108]:
a % b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]], dtype=int32)

In [109]:
a * 10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [110]:
c = a * 10

In [111]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [112]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [113]:
bb = b.reshape(4,2)

In [114]:
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [115]:
# 행렬곱: @
a @ bb

array([[1400, 1500],
       [3480, 3740]])

### numpy의 기본 연산과 조건 처리 2
- numpy의 조건 처리

In [116]:
a = np.arange(1,15)

In [117]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [119]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [120]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [121]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
a[a < 5] = 5

In [123]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
a[a > 10] = 10

In [125]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])